vich_uploader:
    db_driver: orm

    mappings:
        avatar:
            uri_prefix: /avatar
            upload_destination: '%kernel.project_dir%/public/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        imageGame:
            uri_prefix: /image_game
            upload_destination: '%kernel.project_dir%/public/image_game'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
